[project]
name = "day5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shubham Kumar", email = "shubamkumar3039@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "docx>=0.2.4",
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "pypdf>=6.18.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
day5 = "day5:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "resumes",
]
